services:
  mysql:
    container_name: mysql-erp
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=erp
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis-erp
    image: redis:7.4
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    container_name: rabbitmq-erp
    image: rabbitmq:4.0.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

