services:
  mysql:
    container_name: mysql-erp
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=erp
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis-erp
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
