server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/erp?useSSL=false&allowPublicKeyRetrieval=true
    username: ${datasource.dev.mysql.usernames}
    password: ${datasource.dev.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: ${datasource.dev.redis.port}
  rabbitmq:
    host: rabbitmq
    port: ${datasource.dev.rabbitmq.port}
    username: ${datasource.dev.rabbitmq.username}
    password: ${datasource.dev.rabbitmq.password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format_sql: true

