server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/erp?useSSL=false&allowPublicKeyRetrieval=true
    username: ${datasource.dev.usernames}
    password: ${datasource.dev.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format_sql: true

